[package]
name = "euler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire="0.4.0"
factorial="0.2.1"

[[bin]]
path = "./src/main.rs"
name = "euler"